/**
 * Color array
 */
const COLOR_PALETTE = [
    '#ffffff', '#800000', '#469990', '#e6194b', '#42d4f4', '#fabed4', '#aaffc3',
    '#9a6324', '#000075', '#f58231', '#4363d8', '#ffd8b1', '#dcbeff', '#808000',
    '#ffe119', '#911eb4', '#bfef45', '#f032e6', '#3cb44b', '#a9a9a9'
];

/**
 * Draw Rectangle function to draw rectangle on the Objects detected by
 * the object detector
 * @param {*} detections : Bounding boxes generated by the SSD model
 * @param {*} ctx : Canvas context for drawing
 */
export const drawRect = (detections, ctx) =>{
    // Loop through each bounding box
    let i=0;
    detections.forEach(prediction => {
      // Extract boxes and classes
      const [x, y, width, height] = prediction.state.bbox; 
      const text = prediction.state.className; 
      if (text){
        // Set styling
        const color = COLOR_PALETTE[i]
        ctx.strokeStyle = color
        ctx.font = '18px Arial';
    
        // Draw rectangles and text
        ctx.beginPath();   
        ctx.fillStyle = color
        ctx.fillText(text, x, y);
        ctx.rect(x, y, width, height); 
        ctx.stroke();
        i++;
      }
    });
}